server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tDxqnGuK2ztMkTfDwRG
    keySecret: RuBQwc7K628opsNONMija3zP7VMjQ7
    bucketName: srb-file-20220228