server:
  port: 80 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-gateway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务，并自动生成转发路由
      routes:
        - id: service-core
          uri: lb://service-core     # lb://根据服务名称从注册中心获取服务请求地址
          predicates:
            - Path=/*/core/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**


  #- id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
      #匹配后提供服务的路由地址
  #    uri: http://localhost:8001
  #    predicates:
  #     - Path=/payment/get/** # 断言，路径相匹配的进行路由
        #- After=2017-01-20T17:42:47.789-07:00[America/Denver]
        #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
        #- Cookie=username,zzyy
        #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
        #- Host=**.atguigu.com
        #- Method=GET
        #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由